name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'k8s/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/website:${{ github.sha }}
          docker build . -t $IMAGE_ID
          docker push $IMAGE_ID

      - name: Update Kubernetes manifest
        run: |
          # image: 箇所のタグ部分を ${{ github.sha }} に置換
          sed -i "s|image: ghcr.io/${{ github.repository_owner }}/website:.*|image: ghcr.io/${{ github.repository_owner }}/website:${{ github.sha }}|g" k8s/www.yml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/www.yml
          git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
          git push